### PR TITLE
Add `Upload image` link for mobile.

### PR DESCRIPTION
**Pull request by Marius786**
This is to enable full mobile support for images.

### CODE REVIEW

**Comment by maneumann** [comment]
Does it work for you on a mobile device? Testing the patch on Firefox on the desktop is ok, but clicking the link on the mobile browser only leads to the top of the page...

**Comment by denisblum** [comment]
Dear developer,
i use liveblog for publishing text and photos from several events. It will be perfect, if a future version of liveblog contains a button "Select photos" and i can choose a photo from my mobile phone, like apple. Currently i have to use a laptop. And this is very cumbersome if you are sitting in a stadion.
Thankx,
Denis

**Comment by justnorris** [comment]
Closing this PR because feature was implemented with React in version 1.7

**Comment by denisblum** [comment]
Hi all,
yes, with the new version, i'm able to insert a picture. BUT:
I can only make a new picture. I cannot take a picture from my library !!

Other points:
- its a little complicated to write a text. one click on the text area doesnt work - the virtual keyboard doesnt apear.

Tested with iPhone 7 plus.

**Comment by justnorris** [comment]
Hey Denis,
This is actually why I submitted pull request #338 - it's merged an pulled in the repository already, but you have to wait a little bit until the plugin update is released. Alternatively you can download the plugin here from github - but this is bleeding edge, I recommend that you wait for the stable plugin release.

**Pull request closed without merging**
