### PR TITLE
Apply filter `liveblog_active_commands` later on so that hooking works

### PR DESCRIPTION
**Pull request by mikeyarce**
Currently, the filter `liveblog_active_commands` runs early becaue it's being loaded when the plugin class is instantiated.   If you happen to hook into it with a plugin that loads before `liveblog` does, then it does work, but if your plugin loads after `liveblog` then the filter won't apply.

This PR moves the filter to `after_setup_theme` so that it waits for all possible plugins and other functions to load first and then it runs the filter - that makes sure that your hook will be used!

This also updates the Readme with updated instructions.
Fixes second part of #362

### CODE REVIEW

**Comment by sboisvert** [comment]
@mikeyarce Wanna solve the conflict here?
@philipjohn Do you want to give a review and merge if you're good with it after the merge conflict is done?

**Comment by mikeyarce** [comment]
@sboisvert added a better commit message!

**Comment by sboisvert** [comment]
Ugh @philipjohn I didn't mean to merge I just wanted to fix the conflict but the UI wasn't super clear :(

Can you confirm if this is good or if I should revert it?

**Comment by combs** [comment]
hi when can this be merged in? We are stuck waiting for it in our production environment; we need to disable hashtag parsing since it is misfiring wildly on numeric entities for us. (#418)

**Comment by sboisvert** [comment]
@philipjohn I'm going to go ahead and merge this but feel free to revert if you disagree.

Thanks!

**Pull request merged**
