### PR TITLE
Entries that have been updated can now be "deleted"

### PR DESCRIPTION
**Pull request by rebeccahum**
As per #108, entries that were previously edited and then deleted were still being displayed after refresh.

### CODE REVIEW

**Comment by trepmal** [comment]
alternate approach: https://github.com/Automattic/liveblog/pull/159

#159 has some nice conversation on it about things to look out for. Might be good to compare the approaches and see what can be gleaned.

**Comment by philipjohn** [comment]
What do you think @rebeccahum ?

**Comment by rebeccahum** [comment]
@philipjohn both methods work great. Mine modifies the database so it appears correctly with the current code on how comments are rendered, whereas #159 changes the way comments that are "deleted" are rendered.

**Comment by philipjohn** [comment]
Okay, I'm going to close this one in favour of #159. It'd be great to properly clear the entries but it looks like this will cause a frontend DB write which is potentially nasty, especially on a Liveblog.

**Pull request closed without merging**
