### PR TITLE
Feature/fix post global variable

### PR DESCRIPTION
**Pull request by scHarvey**
Plugin was throwing notices of trying to get property of a non-object on $post as it was not defined when it was being referenced. Move to get_post() resolved this on local, dev, and stage environments and get_post is safer in general that direct access to the global.

https://wordpressvip.zendesk.com/hc/en-us/requests/53450

### CODE REVIEW

**Comment by philipjohn** [comment]
Thanks @scHarvey !

Could you share the exact error you're getting, and under what circumstances that occurs please?

Given `get_post()` itself falls back to the `$post` global if a specific post isn't already specified, I'm curious how that gets rid of the error.

I suspect that the problem is with the conditional used - `if ( ! $post )` vs `if ( null !== $this_post )`. Rather than using `get_post()` it looks like we can just tighten the conditional to make it do a better check of `$post`.

One other thing - it looks like this branch needs to be rebased as it includes a couple of extra commits.

**Comment by philipjohn** [comment]
@scHarvey I've had a bash at reproducing this today and so far I'm not successful. If you have any more details on the bug that'd really help. Thanks!

**Comment by scHarvey** [comment]
it was throwing a notice of trying to get a property “ID” of a non-object
on line 384. It would throw this notice on the home screen and the admin.
I’m not sure why that method is even being invoked at that point, but maybe
you have a clearer idea of that.

My only thought on why get_post() works and $post doesn’t is that maybe
get_post returns an empty object or at least fails more gracefully than
just a raw $post reference does. The method “add_display_post_state” uses
get_post instead of the global as well, so I didn’t think this was too big
of a change from the norm.


_______________
Clint Harvey
sch@rw-dev.com
<http://www.clintharvey.net/>  <http://www.twitter.com/scharvey>
<http://facebook.com/scharvey>
<http://www.google.com/profiles/sclintharvey>
<http://packlove.com/human/clint>

**Comment by scHarvey** [comment]
Did a clean install of the plugin on a new branch of our theme, just to
make sure I’m not crazy.


( ! ) Notice: Trying to get property of non-object in
/nfs/majornelson/wp-content/plugins/liveblog/liveblog.php
<nbopen:///nfs/majornelson/wp-content/plugins/liveblog/liveblog.php:381> on
line *381*
Call Stack
#TimeMemoryFunctionLocation
1 0.0020 276496 {main}( ) .../index.php*:*0
<nbopen:///nfs/majornelson/wp/wp-admin/index.php:0>
2 0.0059 336152 require_once( '/nfs/majornelson/wp/wp-admin/admin.php' )
.../index.php*:*10 <nbopen:///nfs/majornelson/wp/wp-admin/index.php:10>
3 0.0079 352904 require_once( '/nfs/majornelson/wp/wp-load.php' )
.../admin.php*:*31 <nbopen:///nfs/majornelson/wp/wp-admin/admin.php:31>
4 0.0138 368808 require_once( '/nfs/majornelson/wp-config.php' )
.../wp-load.php*:*42 <nbopen:///nfs/majornelson/wp/wp-load.php:42>
5 0.0156 470784 require_once( '/nfs/majornelson/wp/wp-settings.php' )
.../wp-config.php*:*116 <nbopen:///nfs/majornelson/wp-config.php:116>
6 2.9078 32261272 do_action( ) .../wp-settings.php*:*392
<nbopen:///nfs/majornelson/wp/wp-settings.php:392>
7 2.9416 32611520
call_user_func_array:{/nfs/majornelson/wp/wp-includes/plugin.php:525}
<http://www.php.net/function.call-user-func-array:%7B/nfs/majornelson/wp/wp-includes/plugin.php:525%7D>
(
) .../plugin.php*:*525
<nbopen:///nfs/majornelson/wp/wp-includes/plugin.php:525>
8 2.9416 32611600 WPCOM_Liveblog::init( ) .../plugin.php*:*525
<nbopen:///nfs/majornelson/wp/wp-includes/plugin.php:525>
9 2.9416 32611840 do_action( ) .../liveblog.php*:*214
<nbopen:///nfs/majornelson/wp-content/plugins/liveblog/liveblog.php:214>
10 2.9416 32613392
call_user_func_array:{/nfs/majornelson/wp/wp-includes/plugin.php:525}
<http://www.php.net/function.call-user-func-array:%7B/nfs/majornelson/wp/wp-includes/plugin.php:525%7D>
(
) .../plugin.php*:*525
<nbopen:///nfs/majornelson/wp/wp-includes/plugin.php:525>
11 2.9417 32613512 WPCOM_Liveblog_Lazyloader::late_load( ) .../plugin.php*:*
525 <nbopen:///nfs/majornelson/wp/wp-includes/plugin.php:525>
12 2.9418 32613728 WPCOM_Liveblog_Lazyloader::is_enabled( )
.../class-wpcom-liveblog-lazyloader.php*:*148
<nbopen:///nfs/majornelson/wp-content/plugins/liveblog/classes/class-wpcom-liveblog-lazyloader.php:148>
13 2.9419 32613872 WPCOM_Liveblog::get_liveblog_state( )
.../class-wpcom-liveblog-lazyloader.php*:*46
<nbopen:///nfs/majornelson/wp-content/plugins/liveblog/classes/class-wpcom-liveblog-lazyloader.php:46>



_______________
Clint Harvey
sch@rw-dev.com
<http://www.clintharvey.net/>  <http://www.twitter.com/scharvey>
<http://facebook.com/scharvey>
<http://www.google.com/profiles/sclintharvey>
<http://packlove.com/human/clint>

**Comment by philipjohn** [comment]
Can you confirm the WordPress and Liveblog version you're on please? I've tried a bunch of times and get nothing at all in the logs.

Also, you mentioned using a different branch of your theme - have you reproduced with other themes? We should rule out anything in your theme mucking up the `$post` variable.

**Comment by scHarvey** [comment]
Sorry, your email hid itself in my “should probably ignore these” folder.

We’re currently on WordPress 4.4.2.1 and this is Liveblog 1.5.

I’ll try another theme, just to verify.


_______________
Clint Harvey
sch@rw-dev.com
<http://www.clintharvey.net/>  <http://www.twitter.com/scharvey>
<http://facebook.com/scharvey>
<http://www.google.com/profiles/sclintharvey>
<http://packlove.com/human/clint>

**Comment by scHarvey** [comment]
Same error with twenty sixteen.


_______________
Clint Harvey
sch@rw-dev.com
<http://www.clintharvey.net/>  <http://www.twitter.com/scharvey>
<http://facebook.com/scharvey>
<http://www.google.com/profiles/sclintharvey>
<http://packlove.com/human/clint>

**Comment by scHarvey** [comment]
Any other ideas on what to look into? This is a VIP site and the
environment we’re developing on it is mature and has been used since the
beginning of the site’s inception, as far as I’m aware. I can make the
plugin throw this notice on any machine we install the site on.


_______________
Clint Harvey
sch@rw-dev.com
<http://www.clintharvey.net/>  <http://www.twitter.com/scharvey>
<http://facebook.com/scharvey>
<http://www.google.com/profiles/sclintharvey>
<http://packlove.com/human/clint>

**Comment by philipjohn** [comment]
@scHarvey What other environments have you tested in? I'm struggling to reproduce anywhere, so I'm finding it really difficult to focus in any closer.

Is it possible that something in your environment is modifying `$post` somewhere?

**Pull request closed without merging**
