### PR TITLE
Add function_exists checks for WP.com functions

### LINKED ISSUE #283: Usage of bump_stats_extras is causing 500 errors in non-WPCOM environments
We're seeing 500 errors coming from multiple functions in wpcom-helper.php because `bump_stats_extras` isn't defined outside WordPress.com. Other plugins that use this function are checking if it exists before instantiating it, so liveblog should too.

### PR DESCRIPTION
**Pull request by mjangda**
Fixes #283

### CODE REVIEW

**Comment by mjangda** [comment]
@bcampeau Let me know if this fixes it for you.

**Comment by bcampeau** [comment]
Exactly how I would have done it. Works for me.

**Comment by mjangda** [comment]
Failed tests are unrelated.

**Comment by mjangda** [comment]
Thanks Brad!

**Pull request merged**
